services:
  - type: static
    name: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - path: /*
        file: dist/index.html
        status: 200
